-- Comprehensive countries data with all regions
-- Run this after the main countries-setup.sql to add all countries

-- Clear existing data first (optional)
-- DELETE FROM countries;

-- Insert comprehensive countries data with proper descriptions, images, and regions
INSERT INTO countries (country_code, country_name, description, image_url, region, processing_info, display_order) VALUES 

-- Oceania
('australia', 'Australia', 'Experience the diverse landscapes of Australia, from the Great Barrier Reef to the Outback. A visa allows travelers to visit vibrant cities like Sydney and Melbourne while enjoying world-class beaches and unique wildlife.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Oceania', 'Processing times vary by visa type. Tourist visas typically processed within 15-25 working days.', 1),
('new_zealand', 'New Zealand', 'Discover New Zealand''s pristine natural beauty, from the North Island''s geothermal wonders to the South Island''s dramatic Alps. Experience Maori culture, adventure sports, and stunning landscapes.', 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Oceania', 'Electronic visas available online with processing within 20 working days. Visitor visas for up to 9 months.', 2),

-- North America  
('canada', 'Canada', 'Discover Canada''s stunning natural beauty, from the Rocky Mountains to Niagara Falls. The Canada Tourist Visa allows travelers to explore multicultural cities, pristine wilderness, and experience the warmth of Canadian hospitality.', 'https://images.unsplash.com/photo-1517935706615-2717063c2225?w=400&h=300&fit=crop&crop=entropy&auto=format', 'North America', 'Tourist visas processed within 15-20 working days. Ensure all documentation is complete for faster processing.', 10),
('usa', 'United States', 'Explore the land of opportunity, from New York''s iconic skyline to California''s beaches and the Grand Canyon''s majesty. The USA offers diverse experiences across 50 states, world-class cities, and stunning national parks.', 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=400&h=300&fit=crop&crop=entropy&auto=format', 'North America', 'Visa processing varies by type. Tourist visas (B-1/B-2) typically take 2-4 weeks.', 11),
('mexico', 'Mexico', 'Discover Mexico''s vibrant culture, ancient Mayan ruins, pristine beaches, and delicious cuisine. From Cancun''s turquoise waters to Mexico City''s rich history, experience the warmth of Mexican hospitality.', 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=400&h=300&fit=crop&crop=entropy&auto=format', 'North America', 'Tourist visas processed within 3-5 working days. Many nationalities can enter visa-free.', 12),

-- Europe
('uk', 'United Kingdom', 'Experience the rich history and modern culture of the UK. From London''s iconic landmarks to Scotland''s highlands and Wales'' castles, discover royal palaces, world-class museums, and charming countryside.', 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Standard visitor visas typically processed within 3 weeks. Priority services available.', 20),
('germany', 'Germany', 'Explore Germany''s perfect blend of history and innovation. Visit Berlin''s historic sites, Bavaria''s fairy-tale castles, and experience world-famous Oktoberfest, Christmas markets, and exceptional beer culture.', 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 calendar days. Some cases may take up to 45 days.', 21),
('france', 'France', 'Discover the romance of France, from Paris'' Eiffel Tower to Provence''s lavender fields. Experience world-class cuisine, art, fashion, and the charm of French culture in cities and picturesque villages.', 'https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen tourist visas processed within 15 calendar days. Appointments required at French consulates.', 22),
('italy', 'Italy', 'Experience Italy''s incredible art, history, and cuisine. From Rome''s ancient Colosseum to Venice''s canals and Tuscany''s wine regions, Italy offers unparalleled cultural treasures and culinary delights.', 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas typically processed within 15 days. Premium services available for faster processing.', 23),
('spain', 'Spain', 'Explore Spain''s passionate culture, from flamenco dancing to world-class museums. Enjoy Barcelona''s architecture, Madrid''s art scene, Seville''s historic charm, and the beautiful Balearic Islands.', 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 calendar days. Online appointment system required.', 24),
('netherlands', 'Netherlands', 'Discover the Netherlands'' tulip fields, historic windmills, and charming canals. Experience Amsterdam''s vibrant culture, cycling-friendly cities, and the country''s innovative approach to modern living.', 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visa processing typically takes 15 days. VFS Global handles applications in many countries.', 25),
('switzerland', 'Switzerland', 'Experience Switzerland''s breathtaking Alpine scenery, pristine lakes, and charming villages. From skiing in the Alps to exploring Zurich and Geneva, enjoy world-class chocolate and luxury watches.', 'https://images.unsplash.com/photo-1530841344095-dbf87fe7906b?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 days. Higher fees apply for Swiss visa applications.', 26),
('norway', 'Norway', 'Discover Norway''s stunning fjords, northern lights, and midnight sun. Experience Oslo''s modern culture, Bergen''s colorful houses, and the dramatic beauty of the Norwegian landscape.', 'https://images.unsplash.com/photo-1464822759531-bb47a484fcad?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas typically processed within 15 days. Norway is not in the EU but part of Schengen.', 27),
('sweden', 'Sweden', 'Experience Sweden''s natural beauty, from Stockholm''s archipelago to Lapland''s wilderness. Discover modern Scandinavian design, IKEA''s homeland, and the concept of "lagom" - balanced living.', 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 calendar days. Online application system available.', 28),
('denmark', 'Denmark', 'Explore Denmark''s hygge culture, fairy-tale castles, and Copenhagen''s colorful Nyhavn harbor. Experience the home of LEGO, world-class design, and some of the world''s happiest people.', 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 days. Denmark offers efficient online services for applications.', 29),
('turkey', 'Turkey', 'Discover Turkey''s unique position bridging Europe and Asia. From Istanbul''s historic mosques and Cappadocia''s fairy chimneys to Mediterranean beaches and rich Ottoman heritage.', 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'E-visas available online with quick processing. Tourist visas typically approved within 24 hours.', 30),

-- Asia
('china', 'China', 'Explore China''s rich history and modern marvels, from the Great Wall to Shanghai''s skyline. A Chinese visa opens doors to ancient temples, bustling markets, and incredible cuisine across this vast and diverse nation.', 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Single-entry tourist visas typically processed within 4 working days with all required documents.', 40),
('singapore', 'Singapore', 'Experience the perfect blend of tradition and innovation in Singapore. This city-state offers world-class shopping, dining, and attractions, from Marina Bay Sands to the vibrant hawker centers and lush Gardens by the Bay.', 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Tourist visas processed quickly, typically within 1-3 working days for most applicants.', 41),
('japan', 'Japan', 'Experience Japan''s perfect blend of ancient tradition and cutting-edge technology. From Tokyo''s neon-lit streets to Kyoto''s serene temples, enjoy world-class cuisine, cherry blossoms, and warm hospitality.', 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Tourist visas typically processed within 5-7 working days. Multiple-entry visas available.', 42),
('south_korea', 'South Korea', 'Discover South Korea''s dynamic culture, from K-pop and Korean BBQ to ancient palaces and modern Seoul. Experience the Korean Wave, beautiful temples, and innovative technology.', 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Tourist visas processed within 5-7 working days. K-ETA available for eligible countries.', 43),
('thailand', 'Thailand', 'Explore the Land of Smiles with its stunning beaches, ancient temples, and delicious street food. From Bangkok''s bustling markets to Phuket''s crystal-clear waters and Chiang Mai''s cultural treasures.', 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Tourist visas processed within 3-5 working days. Many nationalities eligible for visa exemption.', 44),
('vietnam', 'Vietnam', 'Experience Vietnam''s rich history, stunning landscapes, and incredible cuisine. From Ha Long Bay''s limestone karsts to Ho Chi Minh City''s energy and the ancient town of Hoi An.', 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'E-visas available online with 3-day processing. Multiple entry options for extended stays.', 45),
('malaysia', 'Malaysia', 'Discover Malaysia''s multicultural diversity, from Kuala Lumpur''s Petronas Towers to Penang''s street food and Borneo''s rainforests. Experience the blend of Malay, Chinese, and Indian cultures.', 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'eVisa system available with quick processing. Many nationalities enjoy visa-free entry.', 46),
('philippines', 'Philippines', 'Explore the Philippines'' 7,641 islands with pristine beaches, vibrant coral reefs, and warm Filipino hospitality. From Palawan''s underground river to Boracay''s white sands and Manila''s history.', 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Visa-free entry available for many countries. Tourist visas processed within 3-5 days when required.', 47),
('india', 'India', 'Experience India''s incredible diversity, from the Taj Mahal''s beauty to Kerala''s backwaters and Rajasthan''s palaces. Discover rich spirituality, diverse cuisines, and colorful festivals.', 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'E-tourist visas available online with 72-hour processing. Multiple entry options available.', 48),
('sri_lanka', 'Sri Lanka', 'Discover the Pearl of the Indian Ocean with its ancient temples, tea plantations, and stunning beaches. Experience Ceylon tea country, wildlife safaris, and warm Sri Lankan hospitality.', 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Electronic Travel Authorization (ETA) available online with quick approval, usually within 24 hours.', 49),
('indonesia', 'Indonesia', 'Explore Indonesia''s 17,000 islands, from Bali''s beaches and temples to Jakarta''s urban energy and Yogyakarta''s cultural heritage. Experience diverse cultures, volcanoes, and tropical paradise.', 'https://images.unsplash.com/photo-1555400603-74a6ba2c1f3e?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Visa on arrival available at major airports. E-visa system for extended stays and multiple entries.', 50),

-- Middle East
('uae', 'United Arab Emirates', 'Discover the UAE''s blend of traditional culture and futuristic cities. From Dubai''s towering skyscrapers and luxury shopping to Abu Dhabi''s cultural attractions, the UAE offers unforgettable experiences in the heart of the Middle East.', 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'Tourist visas available with quick processing, often approved within 1-2 working days.', 60),
('qatar', 'Qatar', 'Experience Qatar''s modern marvels and rich heritage. From Doha''s futuristic skyline to traditional souqs and world-class museums. Qatar offers luxury experiences and Arabian hospitality.', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'Visa-free entry or visa on arrival for many nationalities. Online visa applications available.', 61),
('saudi_arabia', 'Saudi Arabia', 'Discover Saudi Arabia''s transformation with new tourist attractions, from the futuristic NEOM city to ancient Nabatean ruins at AlUla and the holy cities of Mecca and Medina.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'Tourist visas now available online with quick processing. Multiple entry options for extended stays.', 62),
('israel', 'Israel', 'Explore Israel''s biblical history and modern innovation. From Jerusalem''s religious sites to Tel Aviv''s beaches and the Dead Sea''s therapeutic waters, experience ancient and contemporary culture.', 'https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'Visa-free entry for many countries up to 90 days. Extended visas available for longer stays.', 63),

-- Africa
('south_africa', 'South Africa', 'Experience South Africa''s incredible diversity, from Cape Town''s Table Mountain to Johannesburg''s energy and Kruger National Park''s wildlife. Discover the Rainbow Nation''s beauty and history.', 'https://images.unsplash.com/photo-1484318571209-661cf29a69ea?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'Visa-free entry for many countries. Tourist visas available for extended stays or restricted nationalities.', 70),
('egypt', 'Egypt', 'Explore Egypt''s ancient wonders, from the Pyramids of Giza to the Valley of the Kings. Discover pharaonic treasures, cruise the Nile River, and experience Cairo''s bustling energy.', 'https://images.unsplash.com/photo-1539650116574-75c0c6d73c2e?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'E-visas available online or visa on arrival at major airports. Processing typically within 7 days.', 71),
('morocco', 'Morocco', 'Discover Morocco''s exotic charm, from Marrakech''s vibrant souks to the Sahara Desert''s golden dunes. Experience Berber culture, mint tea, and stunning architecture in this North African gem.', 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'Visa-free entry for many countries up to 90 days. Tourist visas available for extended stays.', 72),
('kenya', 'Kenya', 'Experience Kenya''s incredible wildlife safaris, from the Masai Mara''s great migration to Mount Kenya''s peaks. Discover diverse cultures, beautiful beaches, and world-class conservation efforts.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'E-visas available online with processing within 7 days. Single and multiple entry options available.', 73),

-- South America
('brazil', 'Brazil', 'Explore Brazil''s vibrant culture, from Rio de Janeiro''s beaches and Carnival to the Amazon rainforest. Experience samba music, delicious cuisine, and the warmth of Brazilian hospitality.', 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'E-visas available online for many countries. Processing typically within 5-7 days.', 80),
('argentina', 'Argentina', 'Discover Argentina''s passionate tango culture, world-class wines, and stunning landscapes. From Buenos Aires'' European elegance to Patagonia''s wilderness and Mendoza''s vineyards.', 'https://images.unsplash.com/photo-1589909202802-8c50ba863a7d?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries. Tourist visas available for extended stays when required.', 81),
('chile', 'Chile', 'Experience Chile''s incredible geography, from the Atacama Desert''s otherworldly landscapes to Patagonia''s glaciers. Discover wine regions, vibrant Santiago, and the mysterious Easter Island.', 'https://images.unsplash.com/photo-1544827150-6855c55b5282?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries up to 90 days. Extended visas available for longer stays.', 82),
('peru', 'Peru', 'Explore Peru''s ancient Inca heritage, from Machu Picchu''s majesty to Cusco''s colonial charm. Experience diverse landscapes, incredible cuisine, and rich indigenous cultures throughout this Andean nation.', 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries up to 90 days. Tourist visas available for extended stays.', 83),

-- Additional European Countries
('austria', 'Austria', 'Discover Austria''s imperial grandeur, from Vienna''s palaces to Salzburg''s musical heritage. Experience Alpine beauty, world-class skiing, and the birthplace of Mozart in this cultural heart of Europe.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 days. Austria offers rich cultural experiences year-round.', 31),
('belgium', 'Belgium', 'Explore Belgium''s medieval cities, world-famous chocolates, and diverse culture. From Brussels'' Grand Place to Bruges'' canals, experience the crossroads of European culture and cuisine.', 'https://images.unsplash.com/photo-1559113202-e44bccf4d3fd?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas typically processed within 15 days. Belgium offers rich history and culinary delights.', 32),
('portugal', 'Portugal', 'Experience Portugal''s golden beaches, historic cities, and warm hospitality. From Lisbon''s colorful trams to Porto''s port cellars and the Algarve''s stunning coastline.', 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 calendar days. Portugal offers excellent year-round weather.', 33),
('greece', 'Greece', 'Discover the cradle of Western civilization with ancient ruins, stunning islands, and Mediterranean charm. From Athens'' Acropolis to Santorini''s sunsets and Mykonos'' nightlife.', 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas typically processed within 15 days. Greece offers island-hopping and ancient history.', 34),
('poland', 'Poland', 'Experience Poland''s resilient spirit, from Krakow''s medieval charm to Warsaw''s modern energy. Discover rich history, hearty cuisine, and the beauty of the Tatra Mountains.', 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 days. Poland offers great value and rich cultural heritage.', 35),
('czech_republic', 'Czech Republic', 'Explore the fairy-tale charm of Prague and beyond. Experience medieval castles, world-class beer culture, and the stunning architecture of this Central European gem.', 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 days. Czech Republic offers affordable luxury and rich history.', 36),
('hungary', 'Hungary', 'Discover Hungary''s thermal baths, historic Budapest, and rich cultural heritage. From the Danube''s banks to Lake Balaton''s shores, experience Magyar culture and hospitality.', 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen visas processed within 15 days. Hungary offers thermal spas and beautiful architecture.', 37),
('croatia', 'Croatia', 'Experience Croatia''s stunning Adriatic coast, historic cities, and natural beauty. From Dubrovnik''s walls to Plitvice Lakes and Split''s ancient palace.', 'https://images.unsplash.com/photo-1576314142381-c0b7f0b4b8d4?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'Schengen member since 2023. Visas processed within 15 days. Croatia offers coastal beauty and history.', 38),
('romania', 'Romania', 'Discover Romania''s dramatic landscapes, from Transylvania''s castles to the Carpathian Mountains. Experience medieval towns, folklore, and Dracula''s legendary homeland.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Europe', 'EU member with visa requirements varying by nationality. Romania offers mystical landscapes and history.', 39),

-- Additional Asian Countries  
('cambodia', 'Cambodia', 'Explore Cambodia''s ancient wonders at Angkor Wat and experience Khmer culture. From temple complexes to vibrant markets, discover this Southeast Asian treasure.', 'https://images.unsplash.com/photo-1570366583862-f91883984fde?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'E-visas available online with quick processing. Cambodia offers incredible historical sites.', 51),
('laos', 'Laos', 'Experience the tranquil beauty of Laos, from Luang Prabang''s temples to the Mekong''s peaceful waters. Discover Buddhist culture and pristine natural landscapes.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Visa on arrival available at most entry points. Laos offers peaceful Buddhist culture and nature.', 52),
('myanmar', 'Myanmar', 'Discover Myanmar''s golden temples, ancient cities, and diverse cultures. From Yangon''s Shwedagon Pagoda to Bagan''s temple plains, experience authentic Southeast Asia.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Tourist visas available with processing times varying. Myanmar offers unique cultural experiences.', 53),
('nepal', 'Nepal', 'Experience the roof of the world in Nepal, home to Mount Everest and rich Himalayan culture. From Kathmandu''s temples to trekking adventures, discover mountain majesty.', 'https://images.unsplash.com/photo-1544198365-f5d60b6d8190?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Visa on arrival available at Kathmandu airport. Nepal offers world-class trekking and spiritual experiences.', 54),
('bangladesh', 'Bangladesh', 'Explore Bangladesh''s rich cultural heritage, from the Sundarbans mangroves to historic Dhaka. Experience Bengali culture, river deltas, and warm hospitality.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Tourist visas available with online application system. Bangladesh offers authentic cultural experiences.', 55),
('maldives', 'Maldives', 'Experience paradise in the Maldives with crystal-clear waters, luxury resorts, and pristine beaches. Perfect for honeymoons, diving, and ultimate relaxation.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Visa-free entry for tourists up to 30 days. Maldives offers world-class diving and luxury resorts.', 56),
('brunei', 'Brunei', 'Discover Brunei''s Islamic culture, rainforest beauty, and modern prosperity. From Bandar Seri Begawan''s mosques to pristine jungles, experience Southeast Asian royalty.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Asia', 'Visa-free entry for many countries. Brunei offers luxury travel and pristine nature.', 57),

-- Additional Middle Eastern Countries
('jordan', 'Jordan', 'Explore Jordan''s ancient wonders, from Petra''s rose-red city to the Dead Sea''s healing waters. Experience Bedouin hospitality and biblical history.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'Visa on arrival available at most entry points. Jordan offers incredible historical sites and desert adventures.', 64),
('lebanon', 'Lebanon', 'Discover Lebanon''s Mediterranean charm, from Beirut''s vibrant nightlife to ancient ruins. Experience the crossroads of cultures, delicious cuisine, and warm hospitality.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'Visa on arrival available for many nationalities. Lebanon offers rich history and excellent cuisine.', 65),
('oman', 'Oman', 'Experience Oman''s stunning landscapes, from dramatic fjords to vast deserts. Discover traditional Arabian culture, beautiful beaches, and warm Omani hospitality.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'E-visas available online with quick processing. Oman offers dramatic landscapes and authentic culture.', 66),
('kuwait', 'Kuwait', 'Discover Kuwait''s modern cities, traditional culture, and oil wealth legacy. Experience Middle Eastern hospitality, shopping, and the blend of tradition and modernity.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'E-visas available for many countries. Kuwait offers modern amenities and traditional culture.', 67),
('bahrain', 'Bahrain', 'Explore Bahrain''s island kingdom with its rich pearling heritage, modern Manama, and Formula 1 racing. Experience Gulf culture and hospitality in this compact nation.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Middle East', 'E-visas available online. Bahrain offers modern facilities and traditional Gulf culture.', 68),

-- Additional African Countries
('tanzania', 'Tanzania', 'Experience Tanzania''s wildlife wonders, from Serengeti safaris to Kilimanjaro''s peak. Discover Zanzibar''s spice markets and pristine beaches.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'Visa on arrival available at most entry points. Tanzania offers world-class safari experiences.', 74),
('uganda', 'Uganda', 'Discover Uganda''s incredible wildlife, from mountain gorillas to diverse national parks. Experience the Pearl of Africa''s natural beauty and warm culture.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'E-visas available online. Uganda offers unique gorilla trekking and wildlife experiences.', 75),
('rwanda', 'Rwanda', 'Experience Rwanda''s remarkable transformation and stunning landscapes. From mountain gorillas to rolling hills, discover the land of a thousand hills.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'Visa-free entry for many countries. Rwanda offers incredible gorilla experiences and eco-tourism.', 76),
('ghana', 'Ghana', 'Explore Ghana''s rich culture, from Accra''s vibrant markets to Cape Coast''s historic castles. Experience West African hospitality, music, and heritage.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'Visa on arrival available. Ghana offers rich cultural heritage and warm West African hospitality.', 77),
('nigeria', 'Nigeria', 'Discover Nigeria''s vibrant culture, from Lagos'' energy to diverse landscapes. Experience Nollywood, amazing cuisine, and the dynamic spirit of Africa''s most populous nation.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'Visa on arrival available for many countries. Nigeria offers vibrant culture and business opportunities.', 78),
('ethiopia', 'Ethiopia', 'Explore Ethiopia''s ancient history, from rock churches of Lalibela to the Rift Valley. Discover the birthplace of coffee and unique cultural heritage.', 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Africa', 'E-visas available online. Ethiopia offers ancient history, unique culture, and dramatic landscapes.', 79),

-- Additional North American Countries
('jamaica', 'Jamaica', 'Experience Jamaica''s reggae culture, stunning beaches, and vibrant spirit. From Bob Marley''s homeland to Blue Mountain coffee, discover Caribbean paradise.', 'https://images.unsplash.com/photo-1544654803-b69140b285a1?w=400&h=300&fit=crop&crop=entropy&auto=format', 'North America', 'Visa-free entry for many countries up to 90 days. Jamaica offers reggae culture and beautiful beaches.', 13),
('costa_rica', 'Costa Rica', 'Discover Costa Rica''s incredible biodiversity, from rainforests to pristine beaches. Experience eco-tourism, adventure sports, and the pura vida lifestyle.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'North America', 'Visa-free entry for many countries up to 90 days. Costa Rica offers world-class eco-tourism.', 14),
('panama', 'Panama', 'Explore Panama''s strategic location connecting two continents. From the famous canal to San Blas islands, experience Central American culture and engineering marvels.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'North America', 'Visa-free entry for many countries. Panama offers canal tours and Caribbean coast experiences.', 15),

-- Additional South American Countries
('colombia', 'Colombia', 'Discover Colombia''s diverse landscapes, from Caribbean coasts to Amazon rainforests. Experience vibrant culture, excellent coffee, and the warmth of Colombian people.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries up to 90 days. Colombia offers incredible diversity and culture.', 84),
('ecuador', 'Ecuador', 'Experience Ecuador''s incredible biodiversity, from the Galápagos Islands to Amazon rainforests. Discover colonial Quito and diverse indigenous cultures.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries up to 90 days. Ecuador offers unique wildlife and cultural experiences.', 85),
('bolivia', 'Bolivia', 'Explore Bolivia''s dramatic landscapes, from the Salar de Uyuni salt flats to Lake Titicaca. Experience indigenous culture and stunning high-altitude adventures.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Tourist visas available on arrival for many countries. Bolivia offers unique landscapes and indigenous culture.', 86),
('uruguay', 'Uruguay', 'Discover Uruguay''s charming colonial cities, beautiful beaches, and relaxed culture. From Montevideo''s tango to Punta del Este''s glamour, experience South American elegance.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries up to 90 days. Uruguay offers safe travel and beautiful coastline.', 87),
('paraguay', 'Paraguay', 'Experience Paraguay''s unique Guaraní culture and colonial heritage. Discover Asunción''s history and the authentic South American experience off the beaten path.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'South America', 'Visa-free entry for many countries up to 90 days. Paraguay offers authentic culture and friendly people.', 88),

-- Additional Oceania Countries
('fiji', 'Fiji', 'Experience Fiji''s tropical paradise with pristine beaches, coral reefs, and warm Fijian hospitality. Perfect for diving, snorkeling, and island relaxation.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Oceania', 'Visa-free entry for many countries up to 120 days. Fiji offers world-class diving and island experiences.', 81),
('papua_new_guinea', 'Papua New Guinea', 'Discover Papua New Guinea''s incredible cultural diversity and pristine wilderness. Experience traditional tribal cultures and untouched natural beauty.', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop&crop=entropy&auto=format', 'Oceania', 'Visa on arrival available for many countries. PNG offers unique cultural experiences and pristine nature.', 82)

ON CONFLICT (country_code) DO UPDATE SET
    country_name = EXCLUDED.country_name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    region = EXCLUDED.region,
    processing_info = EXCLUDED.processing_info,
    display_order = EXCLUDED.display_order,
    updated_at = NOW();